### PR TITLE
Seminar presentation Max

### PR DESCRIPTION
**Pull request by maximikos**

### CODE REVIEW

**Comment by volker-krey** [comment]
Many thanks for adding your presentation to the `seminar` folder. I have one additional request: Could you please add a link to the presentation under your name to `seminar/Readme.md`. You can simply push an additional commit with this change to the branch you are working off and it will automatically be added to this pull request.

**Comment by volker-krey** [comment]
Thanks, Max. There is a more elegant a robust way of providing the relative link to a file in the same repository instead of using the full URL. A key difference is that also in case you are viewing a local copy the `Readme.md` you will get pointed to the local copy of the file, not the one on the master branch in the upstream repository. As the presentation sits in the same folder, it is sufficient to just provide the filename in the link (see, e.g., Kamila's presentation).

**Comment by maximikos** [comment]
Thanks for the tip, Volker! Changed it now.

**Review by volker-krey — APPROVED** [review]
Thanks for adjusting. Looks good to me.

**Pull request merged**
