### PR TITLE
cleaning up the presentations folder + Kamila's seminar presentation

### PR DESCRIPTION
**Pull request by kamilakrych**

### CODE REVIEW

**Comment by volker-krey** [comment]
Many thanks for adding your presentation and the cleanup of the presentation folder. I have one additional request: Could you please add a link to the presentation under your name to `seminars/Readme.md `. You can simply push an additional commit with this change to the branch you are working off and it will automatically be added to this pull request.

**Comment by volker-krey** [comment]
One more suggestion: As others are committing the seminar presentations to the `seminar` folder, could you move your presentation file also there, please. The cleanup in the presentations folder can stay as is. Thanks.

**Comment by kamilakrych** [comment]
Done :)

**Comment by volker-krey** [comment]
Thanks.

**Pull request merged**
